-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 19:23:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_pensadores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_pensadores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_pensadores` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `bd_pensadores` ;

-- -----------------------------------------------------
-- Table `bd_pensadores`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pensadores`.`autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `data_nasc` VARCHAR(4) NOT NULL,
  `data_mortem` VARCHAR(4) NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pensadores`.`frase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pensadores`.`frase` (
  `id_frase` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_frase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pensadores`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pensadores`.`livro` (
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(300) NOT NULL,
  `subtitulo` VARCHAR(300) NULL,
  `data_pub` VARCHAR(4) NOT NULL,
  `disponibilidade` VARCHAR(1) NOT NULL DEFAULT 'N',
  `link_disp` VARCHAR(300) NULL,
  `vol` INT NULL,
  `edicao` INT NOT NULL DEFAULT 1,
  `colecao` VARCHAR(300) NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pensadores`.`livro_tem_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pensadores`.`livro_tem_autor` (
  `livro_isbn` INT NOT NULL,
  `id_autor` INT NOT NULL,
  INDEX `fk_livro_has_autor_autor1_idx` (`id_autor` ASC) VISIBLE,
  INDEX `fk_livro_has_autor_livro1_idx` (`livro_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_autor_livro1`
    FOREIGN KEY (`livro_isbn`)
    REFERENCES `bd_pensadores`.`livro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `bd_pensadores`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pensadores`.`pseudonimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pensadores`.`pseudonimo` (
  `id_pseudonimo` INT NOT NULL AUTO_INCREMENT,
  `nome_pseudonimo` VARCHAR(200) NULL,
  `id_autor` INT NOT NULL,
  PRIMARY KEY (`id_pseudonimo`),
  INDEX `fk_pseudonimo_autor1_idx` (`id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_pseudonimo_autor1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `bd_pensadores`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pensadores`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pensadores`.`editora` (
  `id_editora` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(300) NOT NULL,
  `cnpj` VARCHAR(17) NULL,
  `contato` VARCHAR(15) NOT NULL,
  `email` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_editora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pensadores`.`livro_tem_editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pensadores`.`livro_tem_editora` (
  `livro_isbn` INT NOT NULL,
  `id_editora` INT NOT NULL,
  INDEX `fk_livro_has_editora_editora1_idx` (`id_editora` ASC) VISIBLE,
  INDEX `fk_livro_has_editora_livro1_idx` (`livro_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_editora_livro1`
    FOREIGN KEY (`livro_isbn`)
    REFERENCES `bd_pensadores`.`livro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_editora_editora1`
    FOREIGN KEY (`id_editora`)
    REFERENCES `bd_pensadores`.`editora` (`id_editora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pensadores`.`autor_tem_frase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pensadores`.`autor_tem_frase` (
  `autor_id_autor` INT NOT NULL,
  `frase_id_frase` INT NOT NULL,
  INDEX `fk_autor_has_frase_frase1_idx` (`frase_id_frase` ASC) VISIBLE,
  INDEX `fk_autor_has_frase_autor1_idx` (`autor_id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_autor_has_frase_autor1`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `bd_pensadores`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_has_frase_frase1`
    FOREIGN KEY (`frase_id_frase`)
    REFERENCES `bd_pensadores`.`frase` (`id_frase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
